ALTER TABLE posts DROP CONSTRAINT IF EXISTS fk_posts_user;
ALTER TABLE posts DROP CONSTRAINT IF EXISTS fk_posts_parent;
ALTER TABLE posts DROP CONSTRAINT IF EXISTS fk_posts_reply_to;

DROP TABLE IF EXISTS posts CASCADE;