// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth_service_mock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tryingmyb3st/PolyTweet/internal/core/domain"
)

// NewMockAuthRepository creates a new instance of MockAuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthRepository {
	mock := &MockAuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAuthRepository is an autogenerated mock type for the AuthRepository type
type MockAuthRepository struct {
	mock.Mock
}

type MockAuthRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthRepository) EXPECT() *MockAuthRepository_Expecter {
	return &MockAuthRepository_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) GetUser(ctx context.Context, email string) (*domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockAuthRepository_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockAuthRepository_Expecter) GetUser(ctx interface{}, email interface{}) *MockAuthRepository_GetUser_Call {
	return &MockAuthRepository_GetUser_Call{Call: _e.mock.On("GetUser", ctx, email)}
}

func (_c *MockAuthRepository_GetUser_Call) Run(run func(ctx context.Context, email string)) *MockAuthRepository_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_GetUser_Call) Return(user *domain.User, err error) *MockAuthRepository_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockAuthRepository_GetUser_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.User, error)) *MockAuthRepository_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// SaveNewUser provides a mock function for the type MockAuthRepository
func (_mock *MockAuthRepository) SaveNewUser(ctx context.Context, user domain.User) (*domain.User, error) {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SaveNewUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) (*domain.User, error)); ok {
		return returnFunc(ctx, user)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) *domain.User); ok {
		r0 = returnFunc(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.User) error); ok {
		r1 = returnFunc(ctx, user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAuthRepository_SaveNewUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveNewUser'
type MockAuthRepository_SaveNewUser_Call struct {
	*mock.Call
}

// SaveNewUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockAuthRepository_Expecter) SaveNewUser(ctx interface{}, user interface{}) *MockAuthRepository_SaveNewUser_Call {
	return &MockAuthRepository_SaveNewUser_Call{Call: _e.mock.On("SaveNewUser", ctx, user)}
}

func (_c *MockAuthRepository_SaveNewUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockAuthRepository_SaveNewUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAuthRepository_SaveNewUser_Call) Return(user1 *domain.User, err error) *MockAuthRepository_SaveNewUser_Call {
	_c.Call.Return(user1, err)
	return _c
}

func (_c *MockAuthRepository_SaveNewUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User) (*domain.User, error)) *MockAuthRepository_SaveNewUser_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// GetUser provides a mock function for the type MockCache
func (_mock *MockCache) GetUser(ctx context.Context, email string) (*domain.User, error) {
	ret := _mock.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 *domain.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.User, error)); ok {
		return returnFunc(ctx, email)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.User); ok {
		r0 = returnFunc(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_GetUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUser'
type MockCache_GetUser_Call struct {
	*mock.Call
}

// GetUser is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
func (_e *MockCache_Expecter) GetUser(ctx interface{}, email interface{}) *MockCache_GetUser_Call {
	return &MockCache_GetUser_Call{Call: _e.mock.On("GetUser", ctx, email)}
}

func (_c *MockCache_GetUser_Call) Run(run func(ctx context.Context, email string)) *MockCache_GetUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_GetUser_Call) Return(user *domain.User, err error) *MockCache_GetUser_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockCache_GetUser_Call) RunAndReturn(run func(ctx context.Context, email string) (*domain.User, error)) *MockCache_GetUser_Call {
	_c.Call.Return(run)
	return _c
}

// SaveUser provides a mock function for the type MockCache
func (_mock *MockCache) SaveUser(ctx context.Context, user domain.User) error {
	ret := _mock.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.User) error); ok {
		r0 = returnFunc(ctx, user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_SaveUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveUser'
type MockCache_SaveUser_Call struct {
	*mock.Call
}

// SaveUser is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.User
func (_e *MockCache_Expecter) SaveUser(ctx interface{}, user interface{}) *MockCache_SaveUser_Call {
	return &MockCache_SaveUser_Call{Call: _e.mock.On("SaveUser", ctx, user)}
}

func (_c *MockCache_SaveUser_Call) Run(run func(ctx context.Context, user domain.User)) *MockCache_SaveUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.User
		if args[1] != nil {
			arg1 = args[1].(domain.User)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_SaveUser_Call) Return(err error) *MockCache_SaveUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_SaveUser_Call) RunAndReturn(run func(ctx context.Context, user domain.User) error) *MockCache_SaveUser_Call {
	_c.Call.Return(run)
	return _c
}
