// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dummyLogin": {
            "post": {
                "description": "Выдаёт тестовый JWT для указанной роли (admin / user). Для каждой роли возвращается фиксированный UUID пользователя: один и тот же UUID для всех запросов с ролью admin и один и тот же UUID для роли user.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Получить тестовый JWT по роли",
                "parameters": [
                    {
                        "description": "доступны роли: admin, user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_auth_transport_http.DummyLoginDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Тестовый токен",
                        "schema": {
                            "$ref": "#/definitions/internal_features_auth_transport_http.DummyLoginDTOResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос (недопустимое значение роли)",
                        "schema": {
                            "$ref": "#/definitions/github_com_tryingmyb3st_PolyTweet_internal_core_domain.CustomError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_tryingmyb3st_PolyTweet_internal_core_domain.InternalError"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Авторизует пользователя по email и паролю, возвращает JWT. Для авторизации в рамках теста - /dummyLogin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Авторизация по email и паролю",
                "parameters": [
                    {
                        "description": "тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_auth_transport_http.LoginDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Успешная авторизация",
                        "schema": {
                            "$ref": "#/definitions/internal_features_auth_transport_http.LoginDTOResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные учётные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_tryingmyb3st_PolyTweet_internal_core_domain.CustomError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_tryingmyb3st_PolyTweet_internal_core_domain.InternalError"
                        }
                    }
                }
            }
        },
        "/posts/create": {
            "post": {
                "description": "Создает пост длиной \u003c= 280 слов",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Создание поста",
                "parameters": [
                    {
                        "description": "тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_posts_transport_http.CreatePostDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пост создан",
                        "schema": {
                            "$ref": "#/definitions/internal_features_posts_transport_http.CreatePostDTOResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос или content \u003e 280",
                        "schema": {
                            "$ref": "#/definitions/github_com_tryingmyb3st_PolyTweet_internal_core_domain.CustomError"
                        }
                    },
                    "401": {
                        "description": "Неверные учетные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_tryingmyb3st_PolyTweet_internal_core_domain.CustomError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_tryingmyb3st_PolyTweet_internal_core_domain.InternalError"
                        }
                    }
                }
            }
        },
        "/posts/{PostId}": {
            "get": {
                "description": "Ищет пост по ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Posts"
                ],
                "summary": "Поиск поста по ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Post ID",
                        "name": "PostId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пост найден",
                        "schema": {
                            "$ref": "#/definitions/internal_features_posts_transport_http.GetPostByIdDTOResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос",
                        "schema": {
                            "$ref": "#/definitions/github_com_tryingmyb3st_PolyTweet_internal_core_domain.CustomError"
                        }
                    },
                    "401": {
                        "description": "Неверные учетные данные",
                        "schema": {
                            "$ref": "#/definitions/github_com_tryingmyb3st_PolyTweet_internal_core_domain.CustomError"
                        }
                    },
                    "404": {
                        "description": "Пост не найден",
                        "schema": {
                            "$ref": "#/definitions/github_com_tryingmyb3st_PolyTweet_internal_core_domain.CustomError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_tryingmyb3st_PolyTweet_internal_core_domain.InternalError"
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Создаёт нового пользователя и возвращает его данные.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "тело запроса",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_features_auth_transport_http.RegisterDTO"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пользователь создан",
                        "schema": {
                            "$ref": "#/definitions/internal_features_auth_transport_http.RegisterDTOResponse"
                        }
                    },
                    "400": {
                        "description": "Неверный запрос или email уже занят",
                        "schema": {
                            "$ref": "#/definitions/github_com_tryingmyb3st_PolyTweet_internal_core_domain.CustomError"
                        }
                    },
                    "500": {
                        "description": "Внутренняя ошибка сервера",
                        "schema": {
                            "$ref": "#/definitions/github_com_tryingmyb3st_PolyTweet_internal_core_domain.InternalError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_tryingmyb3st_PolyTweet_internal_core_domain.CustomError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "enum": [
                        "INVALID_REQUEST",
                        " INTERNAL_ERROR",
                        " SCHEDULE_EXISTS",
                        " SLOT_ALREADY_BOOKED",
                        " FORBIDEN",
                        " NOT_FOUND"
                    ]
                },
                "message": {
                    "type": "string",
                    "example": "invalid request"
                }
            }
        },
        "github_com_tryingmyb3st_PolyTweet_internal_core_domain.InternalError": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "enum": [
                        "INTERNAL_ERROR"
                    ]
                },
                "message": {
                    "type": "string",
                    "example": "internal server error"
                }
            }
        },
        "internal_features_auth_transport_http.DummyLoginDTO": {
            "type": "object",
            "properties": {
                "role": {
                    "type": "string",
                    "example": "user"
                }
            }
        },
        "internal_features_auth_transport_http.DummyLoginDTOResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_features_auth_transport_http.LoginDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "useremail@gmail.com"
                },
                "password": {
                    "type": "string",
                    "example": "supersecretpass"
                }
            }
        },
        "internal_features_auth_transport_http.LoginDTOResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "internal_features_auth_transport_http.RegisterDTO": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "x-order": "0",
                    "example": "useremail@gmail.com"
                },
                "password": {
                    "type": "string",
                    "x-order": "1",
                    "example": "supersecretpass"
                },
                "role": {
                    "type": "string",
                    "x-order": "2",
                    "example": "admin"
                }
            }
        },
        "internal_features_auth_transport_http.RegisterDTOResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "x-order": "0",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "email": {
                    "type": "string",
                    "x-order": "1",
                    "example": "useremail@gmail.com"
                },
                "password": {
                    "type": "string",
                    "x-order": "2"
                },
                "role": {
                    "type": "string",
                    "x-order": "3",
                    "example": "admin"
                },
                "createdAt": {
                    "type": "string",
                    "x-order": "4",
                    "example": "2026-03-25T12:00:41.267Z"
                }
            }
        },
        "internal_features_posts_transport_http.CreatePostDTO": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "x-order": "0",
                    "example": "Hello, world!"
                },
                "parent_id": {
                    "type": "string",
                    "x-order": "1",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "reply_to": {
                    "type": "string",
                    "x-order": "2",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "image_url": {
                    "type": "string",
                    "x-order": "3",
                    "example": "https://example.com/image.jpg"
                }
            }
        },
        "internal_features_posts_transport_http.CreatePostDTOResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "x-order": "0",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "user_id": {
                    "type": "string",
                    "x-order": "1",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "content": {
                    "type": "string",
                    "x-order": "2",
                    "example": "Hello, world!"
                },
                "parent_id": {
                    "type": "string",
                    "x-order": "3",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "reply_to": {
                    "type": "string",
                    "x-order": "4",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "image_url": {
                    "type": "string",
                    "x-order": "5",
                    "example": "https://example.com/image.jpg"
                },
                "created_at": {
                    "type": "string",
                    "x-order": "6",
                    "example": "2026-03-25T12:00:41.267Z"
                }
            }
        },
        "internal_features_posts_transport_http.GetPostByIdDTOResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "x-order": "0",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "user_id": {
                    "type": "string",
                    "x-order": "1",
                    "example": "3fa85f64-5717-4562-b3fc-2c963f66afa6"
                },
                "content": {
                    "type": "string",
                    "x-order": "2",
                    "example": "Hello, world!"
                },
                "parent_id": {
                    "type": "string",
                    "x-order": "3",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "reply_to": {
                    "type": "string",
                    "x-order": "4",
                    "example": "123e4567-e89b-12d3-a456-426614174000"
                },
                "image_url": {
                    "type": "string",
                    "x-order": "5",
                    "example": "https://example.com/image.jpg"
                },
                "created_at": {
                    "type": "string",
                    "x-order": "6",
                    "example": "2026-03-25T12:00:41.267Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "127.0.0.1:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Poly Twitter Service",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
